//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSDAReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReminderTable
    {
        public int Id { get; set; }
        public string Desc { get; set; }
        public System.DateTime Waktu { get; set; }
    }
}
